### ISSUE TITLE
Documentar planejamento da Sprint 01

### ISSUE THREAD

**Issue by lucaaas** [fga-eps-mds/2017.2-MerendaMais#189]
### Descrição
Faça uma descrição detalhada dessa issue para que todos tenham conhecimento do que ela se trata.

### Label
Adicione no mínimo uma label que corresponda a essa issue.

### Tasks
Escreva todas as tarefas que devem ser realizadas para completar essa issue.  
_Ignorar em issues de dúvidas e bugs_

### Comportamento esperado
Descreva o que deveria acontecer.  
_Usar nas issues de bugs_

### Comportamento real
Descreva o que está acontecendo.  
_Usar nas issues de bugs_

### Onde foi observado esse comportamento
_Usar nas issues de bugs_

- [ ] Aparelho iOS
- [ ] Simulador de iOS
- [ ] Aparelho Android
- [ ] Simulador Android

### Como reproduzir esse comportamento
Descreva os passos necessários para reproduzir o que está acontecendo com você. Quanto mais detalhes, melhor.  
_Usar em issues de bugs_

### Anexos
Links, imagens, trechos de código, etc. que podem facilitar mostrar algum bug ou dúvida. Quanto mais detalhado, melhor.  
_Usar em issues de dúvidas e bugs_

**Comment by andre-filho** [comment]
feito
