### ISSUE TITLE
melhor organização das constantes do arquivo de generalConstants

### ISSUE THREAD

**Issue by andre-filho** [fga-eps-mds/2017.2-MerendaMais#202]
### Descrição
Faça uma descrição detalhada dessa issue para que todos tenham conhecimento do que ela se trata.

### Label
Adicione no mínimo uma label que corresponda a essa issue.

### Tasks
Escreva todas as tarefas que devem ser realizadas para completar essa issue.  
_Ignorar em issues de dúvidas e bugs_

### Comportamento esperado
Descreva o que deveria acontecer.  
_Usar nas issues de bugs_

### Comportamento real
Descreva o que está acontecendo.  
_Usar nas issues de bugs_

### Onde foi observado esse comportamento
_Usar nas issues de bugs_

- [ ] Aparelho iOS
- [ ] Simulador de iOS
- [ ] Aparelho Android
- [ ] Simulador Android

### Como reproduzir esse comportamento
Descreva os passos necessários para reproduzir o que está acontecendo com você. Quanto mais detalhes, melhor.  
_Usar em issues de bugs_

### Anexos
Links, imagens, trechos de código, etc. que podem facilitar mostrar algum bug ou dúvida. Quanto mais detalhado, melhor.  
_Usar em issues de dúvidas e bugs_

**Comment by hugo-asb** [comment]
Resolvidos nos commits:
ec694fc
4ed7ff7
b58f3f4
7295dd0
ec4468d
dc04f00
